# SEMAINE
input_datetime:
  heating_salon_start_1:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_salon_end_1:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_salon_start_2:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_salon_end_2:
    name: "Confort : Fin"
    has_date: false
    has_time: true

# TELETRAVAIL
  heating_salon_start_1_t:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_salon_end_1_t:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_salon_start_2_t:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_salon_end_2_t:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_salon_start_3_t:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_salon_end_3_t:
    name: "Confort : Fin"
    has_date: false
    has_time: true

# WEEKEND
  heating_salon_start_1_w:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_salon_end_1_w:
    name: "Confort : Fin"
    has_date: false
    has_time: true

binary_sensor:
  - platform: template
    sensors:
      heating_salon_1: # SEMAINE
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_salon_start_1') [0:5] %}
          {% set stop = states('input_datetime.heating_salon_end_1') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('input_select.workday') == 'Bureau' 
            and states('binary_sensor.workday_status') == 'on'
            and states('input_boolean.heating_salon_enabled_1') == 'on' }}
      heating_salon_2:
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_salon_start_2') [0:5] %}
          {% set stop = states('input_datetime.heating_salon_end_2') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('input_select.workday') == 'Bureau'
            and states('binary_sensor.workday_status') == 'on'
            and states('input_boolean.heating_salon_enabled_2') == 'on' }}
      heating_salon_1_t: # TELETRAVAIL
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_salon_start_1_t') [0:5] %}
          {% set stop = states('input_datetime.heating_salon_end_1_t') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true 
            and states('input_select.workday') == 'Télétravail'
            and states('binary_sensor.workday_status') == 'on'
            and states('input_boolean.heating_salon_enabled_1_t') == 'on' }}
      heating_salon_2_t:
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_salon_start_2_t') [0:5] %}
          {% set stop = states('input_datetime.heating_salon_end_2_t') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true 
            and states('input_select.workday') == 'Télétravail'
            and states('binary_sensor.workday_status') == 'on'
            and states('input_boolean.heating_salon_enabled_2_t') == 'on' }}
      heating_salon_3_t: 
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_salon_start_3_t') [0:5] %}
          {% set stop = states('input_datetime.heating_salon_end_3_t') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true 
            and states('input_select.workday') == 'Télétravail'
            and states('binary_sensor.workday_status') == 'on'
            and states('input_boolean.heating_salon_enabled_3_t') == 'on' }}
      heating_salon_1_w: # WEEKEND
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_salon_start_1_w') [0:5] %}
          {% set stop = states('input_datetime.heating_salon_end_1_w') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('binary_sensor.not_workday_status') == 'on'
            and states('input_boolean.heating_salon_enabled_1_w') == 'on' }}
      power_rad_salon_dispo:
        friendly_name: Puissance dispo
        value_template: >
          {{ states('sensor.linky_i_sousc') | int *200 - states('sensor.linky_papp') | int <= 2000}} 

input_boolean:
  heating_salon_enabled_1: #SEMAINE
    name: Plage Active
    icon: mdi:toggle-switch
  heating_salon_enabled_2:
    name: Plage Active
    icon: mdi:toggle-switch

  heating_salon_enabled_1_t: #TELETRAVAIL
    name: Plage Active
    icon: mdi:toggle-switch
  heating_salon_enabled_2_t:
    name: Plage Active
    icon: mdi:toggle-switch
  heating_salon_enabled_3_t:
    name: Plage Active
    icon: mdi:toggle-switch

  heating_salon_enabled_1_w: # WEEKEND
    name: Plage Active
    icon: mdi:toggle-switch
  power_rad_salon_ok:
    name: Thermostat activé
    icon: mdi:toggle-switch

script:
  heating_salon_boost:
    alias: Boost Salon
    icon: mdi:timer-outline
    sequence:
    - event: schedy_set_value
      event_data:
        app_name: schedy_heating
        room: salon
        v: '{{ states.input_number.salon_boost_temperature.state }}'
        rescheduling_delay: '{{ states.input_number.heating_salon_time_boost.state }}'

  heating_salon_boost_reset:
    alias: "Boost Salon: Reset"
    icon: mdi:timer-off-outline
    sequence:
    - event: schedy_set_value
      event_data:
        app_name: schedy_heating
        room: salon
        v:  '{{ states.input_number.chambre_salon_temperature.state }}'
        rescheduling_delay: 1

input_number:
  heating_salon_time_boost:
    name: 'Boost : Durée'
    initial: 60
    min: 5
    max: 360
    step: 5
    unit_of_measurement: Min.
    icon: 'mdi:clock'
  salon_boost_temperature:
    name: Température Boost
    min: 14
    max: 26
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  salon_confort_temperature:
    name: Température Confort
    min: 14
    max: 26
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'


sensor:
- platform: template
  sensors:
    temp_up_th_salon: # Pour History Graph
      friendly_name: "Chauffage Température"
      value_template: > 
        {% if is_state('climate.thermostat_salon_2', 'heat') %}
          Chauffe {{state_attr ('climate.thermostat_salon_2', 'temperature')}}°
        {% else %}
          Off
        {% endif %}