# TELETRAVAIL
input_datetime:
  heating_bureau_start_1_t:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_bureau_end_1_t:
    name: "Confort : Fin"
    has_date: false
    has_time: true


# WEEKEND
  heating_bureau_start_1_w:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_bureau_end_1_w:
    name: "Confort : Fin"
    has_date: false
    has_time: true

binary_sensor:
  - platform: template
    sensors:
      heating_bureau_1_t: # TELETRAVAIL
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_bureau_start_1_t') [0:5] %}
          {% set stop = states('input_datetime.heating_bureau_end_1_t') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true 
            and states('input_select.workday') == 'Télétravail'
            and states('input_boolean.heating_bureau_enabled_1_t') == 'on' }}
      heating_bureau_1_w: # WEEKEND
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_bureau_start_1_w') [0:5] %}
          {% set stop = states('input_datetime.heating_bureau_end_1_w') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('binary_sensor.not_workday_status') == 'on'
            and states('input_boolean.heating_bureau_enabled_1_w') == 'on' }}


input_boolean:
  heating_bureau_enabled_1_t: #TELETRAVAIL
    name: Plage Active
    icon: mdi:toggle-switch
  heating_bureau_enabled_1_w: # WEEKEND
    name: Plage Active
    icon: mdi:toggle-switch
  heating_bureau_boost: # WEEKEND
    name: Mode Boost
    icon: mdi:toggle-switch

script:
  heating_bureau_boost:
    alias: Boost bureau
    icon: mdi:timer-outline
    sequence:
    - event: schedy_set_value
      event_data:
        app_name: schedy_heating
        room: bureau
        v: '{{ states.input_number.bureau_boost_temperature.state }}'
        rescheduling_delay: '{{ states.input_number.heating_bureau_time_boost.state }}'

  heating_bureau_boost_reset:
    alias: "Boost bureau: Reset"
    icon: mdi:timer-off-outline
    sequence:
    - event: schedy_set_value
      event_data:
        app_name: schedy_heating
        room: bureau
        v:  '{{ states.input_number.bureau_confort_temperature.state }}'
        rescheduling_delay: 1

input_number:

  heating_bureau_time_boost:
    name: 'Boost : Durée'
    initial: 60
    min: 5
    max: 360
    step: 5
    unit_of_measurement: Min.
    icon: 'mdi:clock'
  bureau_boost_temperature:
    name: Température Boost
    min: 14
    max: 26
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  bureau_confort_temperature:
    name: Température Confort
    min: 14
    max: 26
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'

sensor:
- platform: template
  sensors:
    temp_up_th_bureau: # Pour History Graph
      friendly_name: "Chauffage Température"
      value_template: > 
        {% if is_state('climate.thermostat_bureau', 'heat') %}
          Chauffe {{state_attr ('climate.thermostat_bureau', 'temperature')}}°
        {% else %}
          Off
        {% endif %}