sensor:
  - platform: template
    sensors:
      power_rad_1250:
        value_template: "{{ states('sensor.linky_i_sousc') | int *200 - states('sensor.linky_papp') | int -1250}}"
      power_rad_2000:
        value_template: "{{ states('sensor.linky_i_sousc') | int *200 - states('sensor.linky_papp') | int -2000}}"
      power_rad_1000:
        value_template: "{{ states('sensor.linky_i_sousc') | int *200 - states('sensor.linky_papp') | int -1000}}"
      power_rad_3250:
        value_template: "{{ states('sensor.linky_i_sousc') | int *200 - states('sensor.linky_papp') | int -3250}}"